config/routes.rb
Market::Application.routes.draw do
  resources :units

  resources :genders

  devise_for :users

  resources :product_offers

  resources :products

     namespace :admin do
       resources :product_offers
       resources :products
       resources :units
       resources :genders
     end

  root :to => "product_offers#index"

end

app/models/product.rb
class Product < ActiveRecord::Base
    has_many :product_offers, :dependent => :destroy
    belongs_to :unit
    belongs_to :gender
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout 'admin'
  before_filter :authenticate

  def authenticate
    authenticate_or_request_with_http_basic do |name, pass|
      #User.authenticate(name, pass)
      name == 'admin' && pass == 'mercado'      
    end
  end

  before_filter :load_units, :load_genders, :only=>[:new, :edit, :create, :update]
  # GET /products
  # GET /products.xml
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to([:admin, @product], :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to([:admin, @product], :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(admin_products_url) }
      format.xml  { head :ok }
    end
  end
  
   private
    def load_units
      @units = Unit.all.collect {|c| [c.name,c.id] }
    end
    def load_genders
      @genders = Gender.all.collect {|c| [c.name,c.id] }
    end
  end

  

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.xml
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end
end
  # GET /products/new
  # GET /products/new.xml

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nome do Produto" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code, "Código de Barras" %><br />
    <%= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label :mark, "Marca" %><br />
    <%= f.text_field :mark %>
  </div>
	
	<p><%= f.label :unit_id, "Unidade de Medida" %></p>
  <p><%= f.select :unit_id, @units, :prompt=>"Selecione..." %></p>

	<p><%= f.label :gender_id, "Gênero" %></p>
  <p><%= f.select :gender_id, @genders, :prompt=>"Selecione..." %></p>

  <div class="field">
    <%= f.label :description, "Descrição" %><br />
    <%= f.text_area :description, :rows => 2 %>
  </div>
<br />
  <div class="actions">
   <p><%= f.submit %></p>
  </div>
<% end %>
<br />

app/views/admin/products/edit.html.erb
<h1>Editar Produto</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', [:admin, @product] %> |
<%= link_to 'Voltar', admin_products_path %>

app/views/admin/products/index.html.erb
<h1>Lista de Produtos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Marca</th>
    <th>Descrição</th>

  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= link_to product.name, [:admin, product] %></td>
    <td><%= link_to product.mark, [:admin, product] %></td>
    <td><%= link_to product.description, [:admin, product] %></td>
    <td><%= link_to image_tag('edit.png'), edit_admin_product_path(product) %></td>
    <td><%= link_to image_tag('trash.png'), [:admin, product], :confirm => 'Deseja excluir esse produto?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Produto', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>Novo Produto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @product.name %>
</p>

<p>
  <b>Marca:</b>
  <%= @product.mark %>
</p>

<p>
  <b>Descrição:</b>
  <%= @product.description %>
</p>
<p>
  <b>Gênero:</b>
  <%= @product.gender.name %>
</p>
<p>
  <b>Unidade de Medida:</b>
  <%= @product.unit.name %>
</p>

<%= link_to 'Editar', edit_admin_product_path(@product) %> |
<%= link_to 'Voltar', admin_products_path %>