config/routes.rb
Market::Application.routes.draw do
  resources :units

  resources :genders

  devise_for :users

  resources :product_offers

  resources :products

     namespace :admin do
       resources :product_offers
       resources :products
       resources :units
       resources :genders
     end

  root :to => "product_offers#index"

end

app/models/product_offer.rb
class ProductOffer < ActiveRecord::Base
    validates_uniqueness_of :product_id, :scope => :user_id
    validates_presence_of :product_id
    validates_presence_of :price
    belongs_to :product
    belongs_to :user
    
end

app/controllers/admin/product_offers_controller.rb
class Admin::ProductOffersController < ApplicationController
    layout 'admin'
    
    before_filter :authenticate

    def authenticate
      authenticate_or_request_with_http_basic do |name, pass|
        #User.authenticate(name, pass)
        name == 'admin' && pass == 'mercado'      
      end
    end
    

    before_filter :load_products, :only=>[:new, :edit, :create, :update]

    # GET /product_offers
    # GET /product_offers.xml
    def index
      @product_offers = ProductOffer.all.group_by(&:product_id).map { |k,v| v.min_by(&:price) }
    

      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @product_offers }
      end
    end

    # GET /product_offers/1
    # GET /product_offers/1.xml
    def show
      @product_offer = ProductOffer.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @product_offer }
      end
    end

end

app/controllers/product_offers_controller.rb
class ProductOffersController < ApplicationController
  before_filter :authenticate_user!
  
  before_filter :load_products, :only=>[:new, :edit, :create, :update]
  
  # GET /product_offers
  # GET /product_offers.xml
  def index
    @product_offers = ProductOffer.all
    @products = Product.all
    
  
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @product_offers }
    end
  end

  # GET /product_offers/1
  # GET /product_offers/1.xml
  def show
    @product_offer = ProductOffer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product_offer }
    end
  end

  # GET /product_offers/new
  # GET /product_offers/new.xml
  def new
    @product_offer = ProductOffer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product_offer }
    end
  end

  # GET /product_offers/1/edit
  def edit
    @product_offer = ProductOffer.find(params[:id])
  end

  # POST /product_offers
  # POST /product_offers.xml
  def create
    @product_offer = ProductOffer.new(params[:product_offer])

    respond_to do |format|
      if @product_offer.save
        format.html { redirect_to(@product_offer, :notice => 'Product offer was successfully created.') }
        format.xml  { render :xml => @product_offer, :status => :created, :location => @product_offer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product_offer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /product_offers/1
  # PUT /product_offers/1.xml
  def update
    @product_offer = ProductOffer.find(params[:id])

    respond_to do |format|
      if @product_offer.update_attributes(params[:product_offer])
        format.html { redirect_to(@product_offer, :notice => 'Product offer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product_offer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /product_offers/1
  # DELETE /product_offers/1.xml
  def destroy
    @product_offer = ProductOffer.find(params[:id])
    @product_offer.destroy

    respond_to do |format|
      format.html { redirect_to(product_offers_url) }
      format.xml  { head :ok }
    end
  end
  
   private
    def load_products
      @products = Product.all.collect {|c| ["#{c.name} - #{c.description}", c.id] }
    end
  end

app/helpers/admin/product_offers_helper.rb
module Admin::ProductOffersHelper
end

app/helpers/product_offers_helper.rb
module ProductOffersHelper
end

app/views/product_offers/_form.html.erb
<%= form_for(@product_offer) do |f| %>
  <% if @product_offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_offer.errors.count, "error") %> prohibited this product_offer from being saved:</h2>

      <ul>
      <% @product_offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
    
	<p><%= f.label :product_id, "Produto:" %></p>
    <p><%= f.select :product_id, @products, :prompt=>"Select..." %></p>
  
    <div id="cash"><p>Preço:<h2>R$<%= f.text_field :price %><%= image_tag "../images/cash.png"%></h2></p></div>
  </p>
<br />

  <div class="actions">
    <p><%= f.submit %></p>
  </div>
<br />
<% end %>

app/views/product_offers/edit.html.erb
<h1>Editar Produto</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_offer %> |
<%= link_to 'Voltar', product_offers_path %>

app/views/product_offers/index.html.erb
<h3>Lista de Ofertas Cadastradas
</h3>
<% if @product_offers.size == 0 %>
<p>Nenhum produto ofertado</p>
<% else %>
<p>Voce tem <%= @product_offers.size %> produto(s) cadastrados</p> 
 
<% end %>
<%= link_to image_tag('add.png'), new_product_offer_path %></p>

<%- if current_user -%>


  <%- current_user.product_offers.each do |product_offer| -%>

  <div id="cada">
<%= link_to product_offer.product.name, product_offer %></p>
<%= link_to product_offer.product.description, product_offer %></p>
<%= link_to product_offer.product.code, product_offer %>
	<p><class id="bg_preco">R$<%= product_offer.price %></class></p>
<p>
  <%= link_to image_tag('edit.png'), edit_product_offer_path(product_offer) %>
<%= link_to image_tag('trash.png'), product_offer, :confirm => 'Deseja excluir este produto?', :method => :delete %>
</p>
</div>
<% end %>


<%- else -%>
  <em>Not logged in</em>
<%- end -%>

app/views/product_offers/new.html.erb
<h3>Confira a lista dos produtos cadastrado pelo fornecedor:</h3>
<%= @products %>
<h1>Novo Produto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', product_offers_path %>

app/views/product_offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @product_offer.product_id %>
</p>

<p>
  <b>Price:</b>
  <%= @product_offer.price %>
</p>



<%= link_to 'Editar', edit_product_offer_path(@product_offer) %> |
<%= link_to 'Voltar', product_offers_path %>