config/routes.rb
Market::Application.routes.draw do
  resources :units

  resources :genders

  devise_for :users

  resources :product_offers

  resources :products

     namespace :admin do
       resources :product_offers
       resources :products
       resources :units
       resources :genders
     end

  root :to => "product_offers#index"

end

app/models/gender.rb
class Gender < ActiveRecord::Base
  has_many :products, :dependent => :destroy
end

app/controllers/admin/genders_controller.rb
class Admin::GendersController < ApplicationController
  layout 'admin'
  
  before_filter :authenticate

  def authenticate
    authenticate_or_request_with_http_basic do |name, pass|
      #User.authenticate(name, pass)
      name == 'admin' && pass == 'mercado'      
    end
  end
  
  def index
     @genders = Gender.all

     respond_to do |format|
       format.html # index.html.erb
       format.xml  { render :xml => @genders }
     end
   end

   # GET /genders/1
   # GET /genders/1.xml
   def show
     @gender = Gender.find(params[:id])

     respond_to do |format|
       format.html # show.html.erb
       format.xml  { render :xml => @gender }
     end
   end

   # GET /genders/new
   # GET /genders/new.xml
   def new
     @gender = Gender.new

     respond_to do |format|
       format.html # new.html.erb
       format.xml  { render :xml => @gender }
     end
   end

   # GET /genders/1/edit
   def edit
     @gender = Gender.find(params[:id])
   end

   # POST /genders
   # POST /genders.xml
   def create
     @gender = Gender.new(params[:gender])

     respond_to do |format|
       if @gender.save
         format.html { redirect_to([:admin, @gender], :notice => 'Gender was successfully created.') }
         format.xml  { render :xml => @gender, :status => :created, :location => @gender }
       else
         format.html { render :action => "new" }
         format.xml  { render :xml => @gender.errors, :status => :unprocessable_entity }
       end
     end
   end

   # PUT /genders/1
   # PUT /genders/1.xml
   def update
     @gender = Gender.find(params[:id])

     respond_to do |format|
       if @gender.update_attributes(params[:gender])
         format.html { redirect_to([:admin, @gender], :notice => 'Gender was successfully updated.') }
         format.xml  { head :ok }
       else
         format.html { render :action => "edit" }
         format.xml  { render :xml => @gender.errors, :status => :unprocessable_entity }
       end
     end
   end

   # DELETE /genders/1
   # DELETE /genders/1.xml
   def destroy
     @gender = Gender.find(params[:id])
     @gender.destroy

     respond_to do |format|
       format.html { redirect_to(admin_genders_url) }
       format.xml  { head :ok }
     end
   end


end

app/controllers/genders_controller.rb
class GendersController < ApplicationController
  # GET /genders
  # GET /genders.xml
 
end

app/helpers/admin/genders_helper.rb
module Admin::GendersHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/views/admin/genders/_form.html.erb
<%= form_for([:admin, @gender]) do |f| %>
  <% if @gender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gender.errors.count, "error") %> prohibited this gender from being saved:</h2>

      <ul>
      <% @gender.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nome" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/genders/edit.html.erb
<h1>Editar Gênero</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', [:admin, @gender] %> |
<%= link_to 'Voltar', admin_genders_path %>

app/views/admin/genders/index.html.erb
<h1>Lista de Gêneros</h1>

<table>
  <tr>
    <th>Name</th>

  </tr>

<% @genders.each do |gender| %>
  <tr>
    <td><%= link_to gender.name, [:admin, gender]  %></td>
    <td><%= link_to image_tag('edit.png'), edit_admin_gender_path(gender) %></td>
    <td><%= link_to image_tag('trash.png'), [:admin, gender], :confirm => 'Deseja excluir esse gênero?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Gênero', new_admin_gender_path %>

app/views/admin/genders/new.html.erb
<h1>Novo Gênero</h1>

<%= render 'form' %>

<%= link_to 'Voltar', admin_genders_path %>

app/views/admin/genders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @gender.name %>
</p>


<%= link_to 'Editar', edit_admin_gender_path(@gender) %> |
<%= link_to 'Voltar', admin_genders_path %>