config/routes.rb
Market::Application.routes.draw do
  resources :units

  resources :genders

  devise_for :users

  resources :product_offers

  resources :products

     namespace :admin do
       resources :product_offers
       resources :products
       resources :units
       resources :genders
     end

  root :to => "product_offers#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/admin.html.erb
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Mercado Backend" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
<link rel="shortcut icon" href="../images/market.ico" />
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
	<div id="center">
		<%= link_to 'Melhores Ofertas', admin_product_offers_path %> -
		<%= link_to 'Lista de Produtos', admin_products_path %> - 
		<%= link_to 'Lista de Unidades', admin_units_path %> -
		<%= link_to 'Lista de Gêneros', admin_genders_path %> 
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
 </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Mercado Manager 1.2" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
<link rel="shortcut icon" href="../images/market.ico" />
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
		<div id="user_nav">
		  <% if user_signed_in? %>
		    Bem vindo <%= current_user.email %>, mantenha seus produtos atualizados.
		    <%= link_to image_tag('exit.png'), destroy_user_session_path %>
		  <% else %>
		    <%= link_to "Criar Conta", new_user_registration_path %> - <%= link_to "Login", new_user_session_path %>
		  <% end %>
		</div>
		<div id="center">

      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
	</div>
  </body>
</html>